fn main() -> Result<(), Box<dyn std::error::Error>> {
    tonic_build::configure()
        .build_server(true)
        .build_client(false)
        .compile(
            &[
                "proto/base.proto",
            ],
            &[
                "proto",
            ],
        )?;
    tonic_build::configure()
        .build_server(true)
        .build_client(false)
        .compile(
            &[
                "proto/user.proto",
            ],
            &[
                "proto",
            ],
        )?;
    Ok(())
}