name: Release

on:
  push:
    tags:
      - '*.*.*'

env:
  CARGO_TERM_COLOR: always

jobs:
  ubuntu_release:

    strategy:
      matrix:
        os: [
          ubuntu-18.04,
          ubuntu-20.04,
          ubuntu-22.04,
        ]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - name: Rename file
        run: cp target/release/yura target/release/yura.${{ matrix.os }}
      - name: Upload Artifact
        uses: softprops/action-gh-release@v1
        with:
          files: target/release/yura.${{ matrix.os }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  macos_release:

    strategy:
      matrix:
        os: [
          macos-10.15,
          macos-11,
          macos-12,
        ]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - name: Rename file
        run: cp target/release/yura target/release/yura.${{ matrix.os }}
      - name: Upload Artifact
        uses: softprops/action-gh-release@v1
        with:
          files: target/release/yura.${{ matrix.os }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  windows_release:

    strategy:
      matrix:
        os: [
          windows-2019,
          windows-2022,
        ]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - name: Rename file
        run: cp target/release/yura.exe target/release/yura.${{ matrix.os }}.exe
      - name: Upload Artifact
        uses: softprops/action-gh-release@v1
        with:
          files: target/release/yura.${{ matrix.os }}.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}